name: "Nais Setup CLI"
description: "Setup CLI for the Nais platform"
inputs:
  version:
    description: "Version of nais CLI to install (e.g., 'v3.8.3' or 'latest')"
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: "Determine platform and architecture"
      shell: bash
      id: platform
      run: |
        # Convert Windows paths to Unix-style for bash compatibility
        ACTION_PATH="${{ github.action_path }}"
        ACTION_PATH="${ACTION_PATH//\\//}"
        "$ACTION_PATH/scripts/detect-platform.sh"

    - name: "Get release information"
      shell: bash
      id: release
      env:
        VERSION: ${{ inputs.version }}
      run: |
        # Convert Windows paths to Unix-style for bash compatibility
        ACTION_PATH="${{ github.action_path }}"
        ACTION_PATH="${ACTION_PATH//\\//}"
        "$ACTION_PATH/scripts/get-release.sh"

    - name: "Download and install nais CLI"
      shell: bash
      env:
        TAG_NAME: ${{ steps.release.outputs.tag_name }}
        FILENAME: ${{ steps.platform.outputs.filename }}
      run: |
        # Convert Windows paths to Unix-style for bash compatibility
        ACTION_PATH="${{ github.action_path }}"
        ACTION_PATH="${ACTION_PATH//\\//}"
        "$ACTION_PATH/scripts/install-nais.sh"
