name: "Nais Setup CLI"
description: "Setup CLI for the Nais platform (Linux only)"
author: "nais"
inputs:
  version:
    description: "Version of nais CLI to install (e.g., 'v3.8.3' or 'latest')"
    required: false
    default: "latest"
runs:
  using: "node20"
  main: "dist/index.js"
