on:
  - push
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          cache: false

      - name: Install dependencies
        run: npm install

      - name: Run type checking
        run: npm run typecheck

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build action
        run: npm run build

      - name: Check dist is up to date
        run: |
          if [ -n "$(git status --porcelain dist)" ]; then
            echo "ERROR: dist directory is not up to date. Please run 'npm run build' and commit the changes."
            git status --porcelain dist
            exit 1
          fi

  test-action:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          cache: false

      - name: Install dependencies
        run: npm install

      - name: Build action
        run: npm run build

      - name: Test action (latest version) - direct run
        id: test-action
        run: |
          export INPUT_VERSION="latest"
          export RUNNER_OS="Linux"
          export RUNNER_ARCH="X64"
          node dist/index.js

      - name: Verify nais CLI installation
        run: |
          echo "PATH: $PATH"
          echo "Checking if nais is in PATH..."
          which nais || echo "nais not found in PATH"
          ls -la ~/.local/bin/ || echo "~/.local/bin/ not found"
          if command -v nais &> /dev/null; then
            nais --version
            echo "✅ Latest version installed successfully"
          else
            echo "❌ nais command not found"
            exit 1
          fi

  test-specific-version:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Mise
        uses: jdx/mise-action@v2
        with:
          cache: false

      - name: Install dependencies
        run: npm install

      - name: Build action
        run: npm run build

      - name: Test action (specific version) - direct run
        id: test-specific
        run: |
          export INPUT_VERSION="v3.8.3"
          export RUNNER_OS="Linux"
          export RUNNER_ARCH="X64"
          node dist/index.js

      - name: Verify specific version
        run: |
          echo "PATH: $PATH"
          echo "Checking if nais is in PATH..."
          which nais || echo "nais not found in PATH"
          ls -la ~/.local/bin/ || echo "~/.local/bin/ not found"
          if command -v nais &> /dev/null; then
            nais --version
            version_output=$(nais --version)
            if [[ "$version_output" == *"3.8.3"* ]]; then
              echo "✅ Correct version v3.8.3 installed successfully"
            else
              echo "❌ Expected version v3.8.3, but got: $version_output"
              exit 1
            fi
          else
            echo "❌ nais command not found"
            exit 1
          fi
