on:
  - push
  - pull_request

jobs:
  test-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - name: "Verify nais version (latest)"
        run: |
          nais --version
          echo "Latest version installed successfully"

  test-specific-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          version: "v3.8.3"
      - name: "Verify nais version (specific)"
        run: |
          nais --version
          # Verify it's the expected version
          version_output=$(nais --version)
          if [[ "$version_output" == *"3.8.3"* ]]; then
            echo "Correct version v3.8.3 installed successfully"
          else
            echo "Expected version v3.8.3, but got: $version_output"
            exit 1
          fi

  test-cross-platform:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - name: "Verify nais version (cross-platform)"
        run: |
          nais --version
